config/routes.rb
DeVryEHR::Application.routes.draw do

  resources :recent_activities

  resources :site_configurations
  match "config/:id", to: 'site_configurations#set_config', as: :config

  resources :users
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#signout', via: :delete
  match '/simulation', :to => 'sessions#simulation_mode'
  match '/edit', :to => 'sessions#edit_mode'
  match '/reset_sim', to: 'sessions#reset_sim'
  match '/review', to: 'sessions#review'
  
  resources :lab_report_templates

  match '/home',    :to => 'static_pages#home'

  match '/search',  :to => 'static_pages#search'

  match '/patients/lab_reports/:id', :to => 'patients#lab_reports'
  match '/patients/recents/:id', :to => 'patients#recents'

  
  resources :order_types

  resources :intake_documents

  resources :image_files
  match "image/:id", :to => 'image_files#code_image'

  resources :lab_and_diagnostic_reports

  resources :clinician_orders
  match '/clinician_orders_ajax_new', :to => 'clinician_orders#ajax_new'

  resources :flow_sheet_records
  match '/flow_sheet_records_ajax_new', :to => 'flow_sheet_records#ajax_new'

  root :to => 'static_pages#home'

  resources :medical_administration_records
  match '/medical_administration_records_ajax_new', :to => 'medical_administration_records#ajax_new'

  resources :clinician_notes
  match '/clinician_notes_ajax_new', :to => 'clinician_notes#ajax_new'

  resources :visits

  resources :patients

  resources :sessions

end

app/models/intake_document.rb
# == Schema Information
#
# Table name: intake_documents
#
#  id                           :integer         not null, primary key
#  visit_id                     :integer
#  image_file_id                :integer
#  description                  :string(255)
#  time_recorded                :datetime
#  created_at                   :datetime        not null
#  updated_at                   :datetime        not null
#  minutes_after_start_of_visit :integer
#

class IntakeDocument < ActiveRecord::Base
  attr_accessible :description, :image_file_id, :time_recorded, :visit_id, :minutes_after_start_of_visit
  validates :visit_id, presence: true
  belongs_to :visit
  has_one :image_file
end

app/controllers/intake_documents_controller.rb
class IntakeDocumentsController < ApplicationController
  include SessionsHelper #load up the SessionsHelper functions to help manage the user session
  before_filter :check_site_configuration #make sure a location configuration has been selected.
  before_filter :record_referrer #record referrer in a session varable for the purposes of navigating back to start point after an action is performed.
  def record_referrer
    session[:return_to] = request.url
  end

  # GET /intake_documents
  # GET /intake_documents.json
  def index
    @intake_documents = IntakeDocument.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @intake_documents }
    end
  end

  # GET /intake_documents/1
  # GET /intake_documents/1.json
  def show
    @intake_document = IntakeDocument.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @intake_document }
    end
  end

  # GET /intake_documents/new
  # GET /intake_documents/new.json
  def new
    @intake_document = IntakeDocument.new
    @intake_document.visit_id = params[:visit_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @intake_document }
    end
  end

  # GET /intake_documents/1/edit
  def edit
    @intake_document = IntakeDocument.find(params[:id])
  end

  # POST /intake_documents
  # POST /intake_documents.json
  def create
    @intake_document = IntakeDocument.new(params[:intake_document])

    respond_to do |format|
      if @intake_document.save
        add_recent_activity 'intake document: ' + @intake_document.description, 'intake_document', @intake_document.id, @intake_document.visit_id, request.session_options[:id]
        format.html { redirect_to @intake_document, notice: 'Intake document was successfully created.' }
        format.json { render json: @intake_document, status: :created, location: @intake_document }
      else
        format.html { render action: "new" }
        format.json { render json: @intake_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /intake_documents/1
  # PUT /intake_documents/1.json
  def update
    @intake_document = IntakeDocument.find(params[:id])

    respond_to do |format|
      if @intake_document.update_attributes(params[:intake_document])
        format.html { redirect_to @intake_document, notice: 'Intake document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @intake_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intake_documents/1
  # DELETE /intake_documents/1.json
  def destroy
    @intake_document = IntakeDocument.find(params[:id])
    @intake_document.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/views/intake_documents/_form.html.erb
<%= form_for(@intake_document) do |f| %>
  <% if @intake_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intake_document.errors.count, "error") %> prohibited this intake_document from being saved:</h2>

      <ul>
      <% @intake_document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%if @intake_document.visit_id.blank?%> 
    <div class="span12">
      <%= f.label :visit_id %><br />
      <%= f.number_field :visit_id %>
    </div>
   <% else %>
    <div class="span12">
      <%= f.hidden_field :visit_id %>
    </div>
  <% end %>
  
  <div class="span8">
    <%= f.label :time_recorded, "Document time stamp" %><br />
    <%= f.datetime_select :time_recorded %>
  </div>
  <div class="span4">
    <%= f.label :minutes_after_start_of_visit %><br />
    <%= f.text_field :minutes_after_start_of_visit %>
  </div>
  <div class="span12">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <% unless params[:action] == "new" %>
    <%= f.label :image_file_id %><br />
    <%= f.hidden_field :image_file_id %>
    <% if @intake_document.image_file_id.blank? %>
      <%= link_to "Add Image", new_image_file_path(:intake_document_id => @intake_document.id), :class => "btn" %>
    <% else %>
      <%= image_tag("/image/#{@intake_document.image_file_id}", :alt => "Image") %>
      <div class="btn-toolbar" style="position:relative;">
        <div class="btn-group" style="top:-9px;">
        <%= link_to "change image", edit_image_file_path(:id => @intake_document.image_file_id, :intake_document_id => @intake_document.id), :class => "btn"%> 
        <%= link_to 'Delete image', image_file_path(:id => @intake_document.image_file_id, :intake_document_id => @intake_document.id), confirm: 'Are you sure?', method: :delete, :class => "btn"%> 
        </div>
    <% end %>
  <% end %>

  <div class="btn-group" style="top:0px;">
    <%= f.submit "Save header", class: "btn" %>
  
<% end %>

app/views/intake_documents/_intake_document.html.erb
<div class="icon">
	<% unless intake_document.image_file_id.blank? %>
		<%= link_to image_tag("/image/#{intake_document.image_file_id}", width: 50, height: 65), intake_document %>
	<% else %>
 		<%= link_to image_tag("Document.png", border: 0), intake_document %>
	<% end %>
	<br />
  <%= intake_document.description %> <br />
  <%= intake_document.time_recorded %> <br />
  <% unless session[:simulation_mode] %>
	  <div class="btn-group">
	  	<%= link_to 'Edit', edit_intake_document_path(intake_document), class: "btn" %> 
	  	<%= link_to 'Delete', intake_document, confirm: 'Are you sure?', method: :delete, class: "btn" %>
	  </div>
  <% end %>
</div>

app/views/intake_documents/edit.html.erb
<% content_for :title, "Editing intake documents"%>
<h1>Editing intake document</h1>

<%= render 'form' %>

<%= link_to 'cancel', :back , class: "btn" %>
</div>
</div>

app/views/intake_documents/new.html.erb
<% content_for :title, "New intake document"%>
<h1>New intake document</h1>

<div id="instruction">Step 1: enter intake document header information and save.</div>

<%= render 'form' %>
<%= link_to "Back", :back, :class => "btn"%></div>

</div>

app/views/intake_documents/show.html.erb
<% content_for :title, "Intake document"%>
<p id="notice"><%= notice %></p>
<p>
  <b>Description:</b>
  <%= @intake_document.description %>
</p>

<p>
  <b>Time posted:</b>
  <%= @intake_document.time_recorded %>
</p>
      
      <% if @intake_document.image_file_id.blank? %> 
      <% unless session[:simulation_mode] %>
	      <div id="instruction">Step 2: Upload intake document image</div>
	       	<%= link_to "Add Image", new_image_file_path(:intake_document_id => @intake_document.id), :class => "btn" %>	
   	  <% end %>
      <%else%> 
      <div class="intake-doc-image">
        <%= image_tag("/image/#{@intake_document.image_file_id}", :alt => "Image") %> </div>
        <div class="btn-toolbar">
        <% unless session[:simulation_mode] %>
	        <div class="btn-group">
	        <%= link_to "Change Image", edit_image_file_path(:id => @intake_document.image_file_id, :intake_document_id => @intake_document.id), :class => "btn"%> 
	        <%= link_to 'Delete Image', image_file_path(:id => @intake_document.image_file_id, :intake_document_id => @intake_document.id), confirm: 'Are you sure?', method: :delete, :class => "btn"%> 
	        </div>
        <% end %>
      <% end %>



<% if !session[:simulation_mode] %>
	<div class="btn-group">
	<%= link_to 'Edit header', edit_intake_document_path(@intake_document), class: "btn" %>
	<%= link_to 'Cancel', :back, class: "btn" %>
	</div>
<% else %>
	<%= link_to 'Back', :back, class: "btn" %>
<% end %>
</div>
<p></p>