config/routes.rb
DeVryEHR::Application.routes.draw do

  resources :recent_activities

  resources :site_configurations
  match "config/:id", to: 'site_configurations#set_config', as: :config

  resources :users
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#signout', via: :delete
  match '/simulation', :to => 'sessions#simulation_mode'
  match '/edit', :to => 'sessions#edit_mode'
  match '/reset_sim', to: 'sessions#reset_sim'
  match '/review', to: 'sessions#review'
  
  resources :lab_report_templates

  match '/home',    :to => 'static_pages#home'

  match '/search',  :to => 'static_pages#search'

  match '/patients/lab_reports/:id', :to => 'patients#lab_reports'
  match '/patients/recents/:id', :to => 'patients#recents'

  
  resources :order_types

  resources :intake_documents

  resources :image_files
  match "image/:id", :to => 'image_files#code_image'

  resources :lab_and_diagnostic_reports

  resources :clinician_orders
  match '/clinician_orders_ajax_new', :to => 'clinician_orders#ajax_new'

  resources :flow_sheet_records
  match '/flow_sheet_records_ajax_new', :to => 'flow_sheet_records#ajax_new'

  root :to => 'static_pages#home'

  resources :medical_administration_records
  match '/medical_administration_records_ajax_new', :to => 'medical_administration_records#ajax_new'

  resources :clinician_notes
  match '/clinician_notes_ajax_new', :to => 'clinician_notes#ajax_new'

  resources :visits

  resources :patients

  resources :sessions

end

app/models/site_configuration.rb
# == Schema Information
#
# Table name: site_configurations
#
#  id                                 :integer         not null, primary key
#  location_name                      :string(255)
#  image_file_id                      :integer
#  logo_text                          :string(255)
#  logo_text_color                    :string(255)
#  top_bar_gradient_start_color       :string(255)
#  top_bar_gradient_end_color         :string(255)
#  secondary_bar_gradient_start_color :string(255)
#  secondary_bar_gradient_end_color   :string(255)
#  page_background_color              :string(255)
#  secondary_header_text_color        :string(255)
#  patient_info_box_background_color  :string(255)
#  created_at                         :datetime        not null
#  updated_at                         :datetime        not null
#

class SiteConfiguration < ActiveRecord::Base
  attr_accessible :image_file_id, :location_name, :logo_text, :logo_text_color, :page_background_color, :page_background_color, :patient_info_box_background_color, :secondary_bar_gradient_end_color, :secondary_bar_gradient_start_color, :secondary_header_text_color, :top_bar_gradient_end_color, :top_bar_gradient_start_color
end

app/controllers/site_configurations_controller.rb
class SiteConfigurationsController < ApplicationController
  include SessionsHelper #load up the SessionsHelper functions to help manage the user session
  before_filter :clear_patient  #clear out the selected patient because the user has browsed away from the patient detail page

  # GET /site_configurations
  # GET /site_configurations.json
  def index
    clear_patient
    @site_configurations = SiteConfiguration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @site_configurations }
    end
  end

  # GET /site_configurations/1
  # GET /site_configurations/1.json
  def show
    @site_configuration = SiteConfiguration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site_configuration }
    end
  end

  # GET /site_configurations/new
  # GET /site_configurations/new.json
  def new

    #set up some devault settings the user can edit
    @site_configuration = SiteConfiguration.new(location_name: "DeVry", logo_text: "Simulation EHR", logo_text_color: "FFFFFF", top_bar_gradient_start_color: "111111", top_bar_gradient_end_color: "444444", secondary_bar_gradient_start_color: "999999", secondary_bar_gradient_end_color: "CCCCCC", secondary_header_text_color: "282842", page_background_color: "FFFFFF", patient_info_box_background_color: "FFFFFF")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site_configuration }
    end
  end

  # GET /site_configurations/1/edit
  def edit
    @site_configuration = SiteConfiguration.find(params[:id])
  end

  def set_config
    @site_configuration = SiteConfiguration.find(params[:id])
    cookies.delete :site_configuration_id #this step might not be necessary
    cookies.permanent[:site_configuration_id] = params[:id] #save the site configuration ID in a permanent cookie so it won't be necessary to reconfigure the site the next time the browser goes to it
    redirect_to site_configurations_path
  end

  # POST /site_configurations
  # POST /site_configurations.json
  def create
    @site_configuration = SiteConfiguration.new(params[:site_configuration])

    respond_to do |format|
      if @site_configuration.save
        format.html { redirect_to @site_configuration, notice: 'Site configuration was successfully created.' }
        format.json { render json: @site_configuration, status: :created, location: @site_configuration }
      else
        format.html { render action: "new" }
        format.json { render json: @site_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /site_configurations/1
  # PUT /site_configurations/1.json
  def update
    @site_configuration = SiteConfiguration.find(params[:id])

    respond_to do |format|
      if @site_configuration.update_attributes(params[:site_configuration])
        format.html { redirect_to @site_configuration, notice: 'Site configuration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site_configuration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_configurations/1
  # DELETE /site_configurations/1.json
  def destroy
    @site_configuration = SiteConfiguration.find(params[:id])
    @site_configuration.destroy
    if @site_configuration == cookies[:site_configuration_id]
      cookies.delete :site_configuration_id
    end

    respond_to do |format|
      format.html { redirect_to site_configurations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/site_configurations_helper.rb
module SiteConfigurationsHelper
end

app/views/site_configurations/_form.html.erb
<%= form_for(@site_configuration) do |f| %>
  <% if @site_configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_configuration.errors.count, "error") %> prohibited this site_configuration from being saved:</h2>

      <ul>
      <% @site_configuration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row-fluid">
  <div class="span4">
    <%= f.label :location_name %><br />
    <%= f.text_field :location_name %>
  </div>
    <div class="span4">
    <%= f.label :logo_text %><br />
    <%= f.text_field :logo_text %>
  </div>
  <div class="span4">
    <%= f.label :logo_text_color %><br />
    <%= f.text_field :logo_text_color, class: "color" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <% unless params[:action] == "new" %>
      <%= f.label :image_file_id %><br />
      <%= f.hidden_field :image_file_id %>
      <% if @site_configuration.image_file_id.blank? %>
        <%= link_to "Add Image", new_image_file_path(:site_configuration_id => @site_configuration.id), :class => "btn" %>
    <% else %>
        <%= image_tag("/image/#{@site_configuration.image_file_id}", :alt => "Image") %>
        <div class="btn-toolbar" style="position:relative;">
          <div class="btn-group" style="top:-9px;">
          <%= link_to "change image", edit_image_file_path(:id => @site_configuration.image_file_id, :site_configuration_id => @site_configuration.id), :class => "btn"%> 
          <%= link_to 'Delete image', image_file_path(:id => @site_configuration.image_file_id, :site_configuration_id => @site_configuration.id), confirm: 'Are you sure?', method: :delete, :class => "btn"%> 
          </div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row-fluid">

</div>
<div class="row-fluid">
  <div class="span3">
    <%= f.label :top_bar_gradient_start_color %><br />
    <%= f.text_field :top_bar_gradient_start_color, class: "color" %>
  </div>
  <div class="span3">
    <%= f.label :top_bar_gradient_end_color %><br />
    <%= f.text_field :top_bar_gradient_end_color, class: "color" %>
  </div>
  <div class="span3">
    <%= f.label :secondary_bar_gradient_start_color %><br />
    <%= f.text_field :secondary_bar_gradient_start_color, class: "color" %>
  </div>
  <div class="span3">
    <%= f.label :secondary_bar_gradient_end_color %><br />
    <%= f.text_field :secondary_bar_gradient_end_color, class: "color" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span4">
    <%= f.label :page_background_color %><br />
    <%= f.text_field :page_background_color, class: "color" %>
  </div>
  <div class="span4">
    <%= f.label :secondary_header_text_color %><br />
    <%= f.text_field :secondary_header_text_color, class: "color" %>
  </div>
  <div class="span4">
    <%= f.label :patient_info_box_background_color %><br />
    <%= f.text_field :patient_info_box_background_color, class: "color" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12 btn-group">
    <%= f.submit "save configuration", class: "btn" %>
<% end %>

app/views/site_configurations/edit.html.erb
<% content_for :title, "Editing location configuration"%>
<h1>Editing location configuration</h1>

<%= render 'form' %>
<%= link_to 'cancel', site_configurations_path, class: "btn"  %>
</div>
</div>

app/views/site_configurations/index.html.erb
<% content_for :title, "Available location configuration"%>
<h1>Available location configurations</h1>

<div class="row-fluid">
    <div class="span3"><h3>Location name</h3></div>
    <div class="span3"><h3>Image file</h3></div>
    <div class="span3"><h3>Header logo text</h3></div>
</div>

<% @site_configurations.each do |site_configuration| %>
 <% if @site_configuration.image_file_id == site_configuration.image_file_id %> 
  <div class="row-fluid selected">
 <% else %>
  <div class="row-fluid">
 <% end %>
    <div class="span3"><%= site_configuration.location_name %></div>
    <div class="span3">
      <% unless site_configuration.image_file_id.blank? %>
        <%= image_tag("/image/#{site_configuration.image_file_id}", :alt => "Logo Image", width: 200)%>
      <% else %>
        no image yet
      <% end %>
    </div>
    <div class="span3"><%= site_configuration.logo_text %></div>
    <div class="span3 btn-group">

      <%= link_to 'Select', config_path(site_configuration), class: "btn" %>
      <%= link_to 'Edit', edit_site_configuration_path(site_configuration), class: "btn"  %>
      <%= link_to 'Delete', site_configuration, confirm: 'Are you sure?', method: :delete, class: "btn"  %>
    </div>
  </div>
<% end %>

<br/>
<br/>

<div class="row-fluid">
  <div class="offset6 span6">
    <%= link_to 'New location', new_site_configuration_path, class: "btn" %>
  </div>
</div>

app/views/site_configurations/new.html.erb
<% content_for :title, "Editing location configuration"%>
<h1>New location configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', site_configurations_path, class: "btn" %>
</div>

app/views/site_configurations/show.html.erb
<% content_for :title, "Editing location configuration"%>
<p id="notice"><%= notice %></p>

<p>
  <b>Location name:</b>
  <%= @site_configuration.location_name %>
</p>

<% unless @site_configuration.image_file_id.blank? %> 
  <p>
    <b>Image file:</b><br/>
    <%= image_tag("/image/#{@site_configuration.image_file_id}", :alt => "Logo Image") %>
  </p>
<% end %>
<p>
  <b>Logo text:</b>
  <%= @site_configuration.logo_text %>
</p>

<p>
  <b>Logo text color:</b>
  <span style="background-color:#<%=@site_configuration.logo_text_color%>;">
    <%= @site_configuration.logo_text_color %>
  </span>
</p>

<p>
  <b>Top bar gradient start color:</b>
  <span style="background-color:#<%=@site_configuration.top_bar_gradient_start_color%>;">
    <%= @site_configuration.top_bar_gradient_start_color %>
  </span>
</p>

<p>
  <b>Top bar gradient end color:</b>
  <span style="background-color:#<%=@site_configuration.top_bar_gradient_end_color%>;">
    <%= @site_configuration.top_bar_gradient_end_color %>
  </span>
</p>

<p>
  <b>Secondary bar gradient start color:</b>
  <%= @site_configuration.secondary_bar_gradient_start_color %>
</p>

<p>
  <b>Secondary bar gradient end color:</b>
  <%= @site_configuration.secondary_bar_gradient_end_color %>
</p>

<p>
  <b>Page background color:</b>
  <%= @site_configuration.page_background_color %>
</p>

<p>
  <b>Secondary header text color:</b>
  <%= @site_configuration.secondary_header_text_color %>
</p>

<p>
  <b>Page background color:</b>
  <%= @site_configuration.page_background_color %>
</p>

<p>
  <b>Patient info box background color:</b>
  <%= @site_configuration.patient_info_box_background_color %>
</p>


<%= link_to 'Edit', edit_site_configuration_path(@site_configuration) %> |
<%= link_to 'Back', site_configurations_path %>