config/routes.rb
DeVryEHR::Application.routes.draw do

  resources :recent_activities

  resources :site_configurations
  match "config/:id", to: 'site_configurations#set_config', as: :config

  resources :users
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#signout', via: :delete
  match '/simulation', :to => 'sessions#simulation_mode'
  match '/edit', :to => 'sessions#edit_mode'
  match '/reset_sim', to: 'sessions#reset_sim'
  match '/review', to: 'sessions#review'
  
  resources :lab_report_templates

  match '/home',    :to => 'static_pages#home'

  match '/search',  :to => 'static_pages#search'

  match '/patients/lab_reports/:id', :to => 'patients#lab_reports'
  match '/patients/recents/:id', :to => 'patients#recents'

  
  resources :order_types

  resources :intake_documents

  resources :image_files
  match "image/:id", :to => 'image_files#code_image'

  resources :lab_and_diagnostic_reports

  resources :clinician_orders
  match '/clinician_orders_ajax_new', :to => 'clinician_orders#ajax_new'

  resources :flow_sheet_records
  match '/flow_sheet_records_ajax_new', :to => 'flow_sheet_records#ajax_new'

  root :to => 'static_pages#home'

  resources :medical_administration_records
  match '/medical_administration_records_ajax_new', :to => 'medical_administration_records#ajax_new'

  resources :clinician_notes
  match '/clinician_notes_ajax_new', :to => 'clinician_notes#ajax_new'

  resources :visits

  resources :patients

  resources :sessions

end

app/models/lab_and_diagnostic_report.rb
# == Schema Information
#
# Table name: lab_and_diagnostic_reports
#
#  id                           :integer         primary key
#  visit_id                     :integer
#  clinician_order_id           :integer
#  image_file_id                :integer
#  release_delay                :integer
#  visible                      :integer
#  result_text                  :text
#  created_at                   :timestamp       not null
#  updated_at                   :timestamp       not null
#  order_type                   :string(255)
#  time_released                :timestamp
#  sim_session                  :string(255)
#  minutes_after_start_of_visit :integer
#

class LabAndDiagnosticReport < ActiveRecord::Base
  attr_accessible :clinician_order_id, :image_file_id, :release_delay, :result_text, :visible, :visit_id, :order_type, :time_released, :minutes_after_start_of_visit
  validates :visit_id, presence: true
  belongs_to :visit
end

app/controllers/lab_and_diagnostic_reports_controller.rb
class LabAndDiagnosticReportsController < ApplicationController
  include SessionsHelper #load up the SessionsHelper functions to help manage the user session
  before_filter :check_site_configuration #make sure a location configuration has been selected.
  # GET /lab_and_diagnostic_reports
  # GET /lab_and_diagnostic_reports.json
  def index
    @lab_and_diagnostic_reports = LabAndDiagnosticReport.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lab_and_diagnostic_reports }
    end
  end

  # GET /lab_and_diagnostic_reports/1
  # GET /lab_and_diagnostic_reports/1.json
  def show
    @lab_and_diagnostic_report = LabAndDiagnosticReport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lab_and_diagnostic_report }
    end
  end

  # GET /lab_and_diagnostic_reports/new
  # GET /lab_and_diagnostic_reports/new.json
  def new
    @lab_and_diagnostic_report = LabAndDiagnosticReport.new
    @lab_and_diagnostic_report.visit_id = params[:visit_id]
    @order_types = OrderType.all
    @order_type_categories = @order_types.group_by(&:category)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lab_and_diagnostic_report }
    end
  end

  # GET /lab_and_diagnostic_reports/1/edit
  def edit
    @lab_and_diagnostic_report = LabAndDiagnosticReport.find(params[:id])
  end

  # POST /lab_and_diagnostic_reports
  # POST /lab_and_diagnostic_reports.json
  def create
    #@lab_and_diagnostic_report = LabAndDiagnosticReport.new(params[:lab_and_diagnostic_report])
    #@lab_and_diagnostic_report.result_text = "test report"
    params[:order_types].each do |order_type|
      @lab_and_diagnostic_report = LabAndDiagnosticReport.new(params[:lab_and_diagnostic_report])
      @lab_and_diagnostic_report.order_type = order_type
      @lab_and_diagnostic_report.save
      
    end

    respond_to do |format|
      if @lab_and_diagnostic_report.save
        format.html { redirect_to @lab_and_diagnostic_report, notice: 'Lab and diagnostic report was successfully created.' }
        format.js
        #format.json { render json: @lab_and_diagnostic_report, status: :created, location: @lab_and_diagnostic_report }
      else
        format.html { render action: "new" }
        format.js
        #format.json { render json: @lab_and_diagnostic_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lab_and_diagnostic_reports/1
  # PUT /lab_and_diagnostic_reports/1.json
  def update
    @lab_and_diagnostic_report = LabAndDiagnosticReport.find(params[:id])


    respond_to do |format|
      if @lab_and_diagnostic_report.update_attributes(params[:lab_and_diagnostic_report])
        format.html { redirect_to session[:return_to], notice: 'Lab and diagnostic report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lab_and_diagnostic_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lab_and_diagnostic_reports/1
  # DELETE /lab_and_diagnostic_reports/1.json
  def destroy
    @lab_and_diagnostic_report = LabAndDiagnosticReport.find(params[:id])

    respond_to do |format|
      format.html { redirect_to session[:return_to] }
      format.json { head :no_content }
    end
  end
end

app/views/lab_and_diagnostic_reports/_form.html.erb
<%= javascript_tag "$(document).ready(function() {
  
  $('#filter').keyup(function(event) {
    
    if (event.keyCode == 27 || $(this).val() == '') {
      
      $(this).val('');
      
      $('tbody tr').removeClass('visible').show().addClass('visible');
    }
    else {
      filter('ol li', $(this).val());
    }
  });
});

function filter(selector, query) {
  query = $.trim(query); 
  query = query.replace(/ /gi, '|'); 

  $(selector).each(function() {
    ($(this).text().search(new RegExp(query, 'i')) < 0) ? $(this).hide().removeClass('visible') : $(this).show().addClass('visible');
  });
}

function noenter() {
  return !(window.event && window.event.keyCode == 13); }"%>
 <%= form_for(@lab_and_diagnostic_report) do |f| %>
  <% if @lab_and_diagnostic_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lab_and_diagnostic_report.errors.count, "error") %> prohibited this lab_and_diagnostic_report from being saved:</h2>

      <ul>
      <% @lab_and_diagnostic_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row-fluid">
  <%if @lab_and_diagnostic_report.visit_id.blank?%> 
    <div class="span12">
      <%= f.label :visit_id %><br />
      <%= f.number_field :visit_id %>
    </div>
   <% else %>
    <div class="span12">
      <%= f.hidden_field :visit_id %>
    </div>
  <% end %>
  </div>

  <div class="row-fluid">
    <div class="span8">
      <%= f.label :time_released %><br />
      <%= f.datetime_select :time_released %>
    </div> 
    <div class="span4">
      <%= f.label :minutes_after_start_of_visit %><br />
      <%= f.text_field :minutes_after_start_of_visit %>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <%= f.label :visible %><br />
      <%= f.select :visible, [["yes", 1], ["no", 0]]%>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <%= f.label :release_delay %><br />
      <%= f.number_field :release_delay, size: 5%> minutes
    </div>
  </div>

<% unless params[:action] == "edit" %>
  <div id="search">
    <label for="filter">Search Order Types</label> <input type="text" name="filter" value="" id="filter" onkeypress="return noenter()"/>
  </div>

<div id="search-window">
  <h2>Order Type</h2>
  <ol>        
      <% @order_type_categories.keys.sort.each do |category| %>
        <li><h3><%=category%></h3></li>
        <% for order_type in @order_type_categories[category] %>
        <li>
          <%= check_box_tag 'order_types[]', order_type.description %> 
          <%= order_type.description %>
       </li>
        <% end %>
      <% end %>
  </ol>
</div>

<% else %>
  <div class="row-fluid">
    <div class="span12">
      <%= f.label :order_type %><br />
      <%= f.hidden_field :order_type%>
      <div class="uneditable-data">
        <%= @lab_and_diagnostic_report.order_type %>
      </div>
    </div>
  </div>
<% end %>


  <div class="row-fluid">
    <div class="span12">
      <%= f.label :result_text %><br />
      <%= f.text_area :result_text, :class => "tinymce", :rows => 15%>
      <%= tinymce %>
    </div>
  </div>

    <% unless params[:action] == "new" %>
    
  <div class="row-fluid">
    <div class="span12">  
        <%= f.label :image_file_id %><br />
        <%= f.hidden_field :image_file_id %>
        <% if @lab_and_diagnostic_report.image_file_id.blank? %>
          <%= link_to "Add Image", new_image_file_path(:lab_and_diagnostic_report_id => @lab_and_diagnostic_report.id), :class => "btn" %>
        <% else %>
          <%= image_tag("/image/#{@lab_and_diagnostic_report.image_file_id}", :alt => "Image") %>
          <div class="btn-toolbar" style="position:relative;">
            <div class="btn-group" style="top:-9px;">
            <%= link_to "change image", edit_image_file_path(:id => @lab_and_diagnostic_report.image_file_id, :lab_and_diagnostic_report_id => @lab_and_diagnostic_report.id), :class => "btn"%> 
            <%= link_to 'Delete image', image_file_path(:id => @lab_and_diagnostic_report.image_file_id, :lab_and_diagnostic_report_id => @lab_and_diagnostic_report.id), confirm: 'Are you sure?', method: :delete, :class => "btn"%> 
            </div>
        <% end %>
    </div>
  </div>
    
  <% end %>

  <div class="row-fluid">
    <div class="span12">
    <%= f.submit "save", class: "btn" %>
  </div>
<% end %>

app/views/lab_and_diagnostic_reports/_lab_and_diagnostic_report.html.erb
<div class="icon">
  <%= link_to image_tag("Document.png", :border=>0), lab_and_diagnostic_report %><br />
  <%= lab_and_diagnostic_report.order_type %> <br />
  <%= lab_and_diagnostic_report.time_released %>
  <% unless session[:simulation_mode] %>
	  <div class="btn-group">
	  	<%= link_to 'Edit', edit_lab_and_diagnostic_report_path(lab_and_diagnostic_report), class: "btn" %> 
	  	<%= link_to 'Delete', lab_and_diagnostic_report, confirm: 'Are you sure?', method: :delete, class: "btn" %>
	  </div>
  <% end %>
</div>

app/views/lab_and_diagnostic_reports/create.js.erb
$('#lab_and_diagnostic_report').html("<%=j render @lab_and_diagnostic_report %>");

app/views/lab_and_diagnostic_reports/edit.html.erb
<% content_for :title, "Editing lab and diagnostic report"%>
<h1>Editing lab and diagnostic report</h1>

<%= render 'form' %>

<%= link_to 'Cancel', session[:return_to], class: "btn" %>

app/views/lab_and_diagnostic_reports/new.html.erb
<% content_for :title, "New lab or diagnostic report"%>
<h1>New lab or diagnostic report</h1>

<%= render 'form' %>

<%= link_to 'Cancel', session[:return_to], class: "btn" %>

app/views/lab_and_diagnostic_reports/show.html.erb
<% content_for :title, "Lab report"%>
<p id="notice"><%= notice %></p>

<h2>  <%= @lab_and_diagnostic_report.order_type %></h2>



<p>
  <b>released at:</b>
  <%= @lab_and_diagnostic_report.time_released %>
</p>



<% if @lab_and_diagnostic_report.image_file_id.blank? %> 
<% unless session[:simulation_mode] %>
  <div id="instruction">Step 2: Upload diagnostic image (optional)</div>
    <%= link_to "Add Image", new_image_file_path(:lab_and_diagnostic_report_id => @lab_and_diagnostic_report.id), :class => "btn" %>  
<% end %>
<%else%> 
<div class="intake-doc-image">
  <%= image_tag("/image/#{@lab_and_diagnostic_report.image_file_id}", :alt => "Image") %> </div>
  <div class="btn-toolbar">
  <% unless session[:simulation_mode] %>
    <div class="btn-group">
    <%= link_to "Change Image", edit_image_file_path(:id => @lab_and_diagnostic_report.image_file_id, :lab_and_diagnostic_report_id => @lab_and_diagnostic_report.id), :class => "btn"%> 
    <%= link_to 'Delete Image', image_file_path(:id => @lab_and_diagnostic_report.image_file_id, :lab_and_diagnostic_report_id => @lab_and_diagnostic_report.id), confirm: 'Are you sure?', method: :delete, :class => "btn"%> 
    </div>
  <% end %>
<% end %>
<p>
  <h3>Note</h3>
  <div class="note">
    <%=raw @lab_and_diagnostic_report.result_text %>
  </div>  
</p>

<% unless session[:simulation_mode] %>
  <%= link_to 'Edit', edit_lab_and_diagnostic_report_path(@lab_and_diagnostic_report), class: "btn"%> 
<% end %>
<%= link_to 'Done', session[:return_to], class: "btn" %>